### ISSUE TITLE
Tests fail on Max OS X

### ISSUE THREAD

**Issue by k88hudson** [mysticatea/cpx#10]
After #8 is fixed, the following tests fail on Max OSX 10.10.2:

```
  The copy method
    should copy specified file blobs:
      ✓ lib async version.
      ✓ lib sync version.
      ✓ command version. (194ms)
    should clean and copy specified file blobs when give clean option:
      ✓ lib async version.
      ✓ lib sync version.
      ✓ command version. (196ms)
    should copy with transform if specified command option.
      ✓ command version. (289ms)
    should copy with transform if specified transform option.
      ✓ lib async version.
      ✓ should throw an error on lib sync version (cannot use streaming api).
      ✓ command version. (206ms)
    should keep order even if -c and -t are mixed.
      ✓ command version. (303ms)

  The watch method
    should copy specified file blobs at first:
      ✓ lib version.
      ✓ command version. (215ms)
    should clean and copy specified file blobs at first when give clean option:
      ✓ lib version.
      ✓ command version. (226ms)
    should copy on file added:
      1) lib version.
      ✓ command version. (401ms)
    should do nothing on file added if unmatch file globs:
      ✓ lib version. (177ms)
      2) "after each" hook

  17 passing (3s)
  2 failing

  1) The watch method should copy on file added: lib version.:
     Uncaught AssertionError: expected null to equal 'added'
      at verifyFiles (test/watch.js:282:36)
      at test/watch.js:291:13
      at Cpx.listener (test/watch.js:57:9)
      at lib/cpx.js:222:19
      at WriteStream.done (lib/copy.js:43:5)
      at finishMaybe (_stream_writable.js:484:14)
      at endWritable (_stream_writable.js:493:3)
      at WriteStream.Writable.end (_stream_writable.js:459:5)
      at ReadStream.onend (_stream_readable.js:505:10)
      at _stream_readable.js:908:16

  2) The watch method "after each" hook:
     Uncaught Error: ENOENT, open 'test-ws/b/a.txt'
      at Error (native)
```

**Comment by mysticatea** [comment]
I also had found it while inspecting #5.
On Mac, if added new file immediately after other files removed, `chokider` looks to not notify file-added events....
But I need more inspecting....
